### ISSUE TITLE
required field "Auto layout file types" in control panel doesn't show any choices

### ISSUE THREAD

**Issue by tkimnguyen** [collective/collective.documentviewer#50]
"libreoffice" package is installed on the server but possibly isn't on the ZEO client's path. This field has no choices but because it's required it prevents changing any other settings.

This is with collective.documentviewer 3.0.2 and Plone 4.3.6 on CentOS 7.0.1406.

![screen shot 2015-07-03 at jul 3 10 14 06 am](https://cloud.githubusercontent.com/assets/815418/8501572/731ca092-216c-11e5-92b4-5dbe33bbdcf4.jpg)

**Comment by vangheem** [comment]
That doesn't have anything to do with libreoffice installation. That vocabulary for that field is a constant.

There is something else wrong going on.

This have any relation to https://github.com/zopefoundation/z3c.form/commit/6aade692fed1d8f7b0d49f56306af732e2ae7bd1 and https://github.com/plone/Products.CMFPlone/issues/530 ?

Someone should fix that...

**Comment by vangheem** [comment]
fixed: https://github.com/zopefoundation/z3c.form/commit/ab2080a9cd69797167b09eb984787857bcc4d59e

you can downgrade z3c.form for now to fix.

**Comment by tkimnguyen** [comment]
Wow, talk about service! :+1: Thanks!
