### ISSUE TITLE
4.0.1 release (4.0.0 breaks on ImportError)

### ISSUE THREAD

**Issue by gyst** [collective/collective.documentviewer#53]
Hi Nathan,

Can we have a 4.0.1 (or 4.1) release? We depend on c261d8aff26 in ploneintranet and I'd rather not release our own egg with a source dependency.

**Comment by gyst** [comment]
Talking to @pilz he indicated it's actually 4fbc47b6f we need, since the instance halts without that fix. Would seem to suggest that 4.0.0 is a brownbag release.

**Comment by vangheem** [comment]
Sure thing. One minute.

**Comment by vangheem** [comment]
done: https://pypi.python.org/pypi/collective.documentviewer/4.0.1
